### ISSUE TITLE
Bugs in authentication

### ISSUE THREAD

**Issue by ErR0rpj** [sumitsojha88/Puzzle_Quiz#6]
User login check when app is opened. 
Pressing back after home page returns us to login page even if we are logged in.
Password and email checking.
Register page and login page UI bug.

**Comment by ErR0rpj** [comment]
T&C checkbox.
Update T&C by making "Terms and condition" a hyperlink.

**Comment by ErR0rpj** [comment]
Pressing back button after loading screen again opens loading screen instead of exiting the app.

**Comment by sumitsojha88** [comment]
Everything is working fine now
